name: Run Pytest

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install black
          pip install ruff
      
      - name: Run Ruff (Linting)
        run: ruff check .
      
      - name: Check formatting with Black
        run: black --check .

      - name: Run tests
        run: pytest
